### ISSUE TITLE
Add interval function

### ISSUE THREAD

**Issue by Widdershin** [Widdershin/cycle-animation-driver#7]
Currently using things like `Observable.interval` is not great if you want to use `cycle-restart`, as time is actually a side effect and should come from drivers.

To that end, it would be very useful to implement an interval call, something like:

``` js
function main({Animation}) {
  const interval$ = Animation.interval(1000);
}
```

I would love help, and am happy to support anyone who wants to take a crack at this.

**Comment by jeetiss** [comment]
#8

**Comment by fuunnx** [comment]
Too bad for non-rx users to have to include the whole `rx` library (300kb ungziped) with it.

I'd suggest to do something like that:
```
var interval = require('rxjs/observable/interval').interval // ~40kb
// (...)
stream.interval = function (period) {
  return interval(period)
};
```

Maybe there is room for better optimisations?
I'd be happy to open a pull request =)

**Comment by Widdershin** [comment]
Very reasonable, but this entire library is about to be superceded by http://github.com/cyclejs/time, so it's probably not worth it at this point. 😄
